class Currency {
  Currency({
    required this.currencyImage,
    required this.currencyName,
    required this.currencySymbolName,
    required this.buyPrice,
    required this.sellPrice,
    required this.lastPrice,
    required this.changedValueOfDay,
    required this.changedPercentageOfDay,
    required this.changedPercentageOfWeek,
    required this.changedPercentageOfMonth,
    required this.changedPercentageOfThreeMonth,
    required this.changedPercentageOfYear,
    required this.minimumValueOfDay,
    required this.maximumValueOfDay,
    required this.minimumValueOfMonth,
    required this.maximumValueOfMonth,
    required this.minimumValueOfYear,
    required this.maximumValueOfYear,
  });

  final String currencyImage;
  final String currencyName;
  final String currencySymbolName;
  double buyPrice;
  double sellPrice;
  double lastPrice;
  double changedValueOfDay;
  double changedPercentageOfDay;
  double changedPercentageOfWeek;
  double changedPercentageOfMonth;
  double changedPercentageOfThreeMonth;
  double changedPercentageOfYear;
  double minimumValueOfDay;
  double maximumValueOfDay;
  double minimumValueOfMonth;
  double maximumValueOfMonth;
  double minimumValueOfYear;
  double maximumValueOfYear;

  // Para fiyatını döndüren fonksiyon
  double getPrice(String type) {
    switch (type) {
      case 'buy':
        return buyPrice;
      case 'sell':
        return sellPrice;
      case 'last':
        return lastPrice;
      default:
        return lastPrice;
    }
  }
}

List<Currency> risingExchangesOfDay = [
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/375px-Flag_of_Thailand.svg.png',
    currencyName: 'Tayland Bahtı',
    currencySymbolName: 'THB',
    buyPrice: 1.0013,
    sellPrice: 1.0014,
    lastPrice: 1.0014,
    changedValueOfDay: 0.01,
    changedPercentageOfDay: 0.88,
    changedPercentageOfWeek: 1.27,
    changedPercentageOfMonth: -2.04,
    changedPercentageOfThreeMonth: 1.95,
    changedPercentageOfYear: 22.19,
    minimumValueOfDay: 0.0027,
    maximumValueOfDay: 1.0013,
    minimumValueOfMonth: 0.0026,
    maximumValueOfMonth: 1.0209,
    minimumValueOfYear: 0.0022,
    maximumValueOfYear: 1.0573,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/300px-Flag_of_South_Africa.svg.png',
    currencyName: 'Güney Afrika Randı',
    currencySymbolName: 'ZAR',
    buyPrice: 1.9163,
    sellPrice: 1.9174,
    lastPrice: 1.9174,
    changedValueOfDay: 0.01,
    changedPercentageOfDay: 0.67,
    changedPercentageOfWeek: 1.43,
    changedPercentageOfMonth: -1.89,
    changedPercentageOfThreeMonth: 1.91,
    changedPercentageOfYear: 25.43,
    minimumValueOfDay: 1.8981,
    maximumValueOfDay: 1.9183,
    minimumValueOfMonth: 1.8624,
    maximumValueOfMonth: 1.9893,
    minimumValueOfYear: 1.5136,
    maximumValueOfYear: 2.0081,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/375px-Flag_of_Georgia.svg.png',
    currencyName: 'Gürcistan Larisi',
    currencySymbolName: 'GEL',
    buyPrice: 12.6597,
    sellPrice: 12.6718,
    lastPrice: 12.6718,
    changedValueOfDay: 0.05,
    changedPercentageOfDay: 0.41,
    changedPercentageOfWeek: 0.61,
    changedPercentageOfMonth: 1.38,
    changedPercentageOfThreeMonth: 0.97,
    changedPercentageOfYear: 19.18,
    minimumValueOfDay: 0.8219,
    maximumValueOfDay: 12.6597,
    minimumValueOfMonth: 0.8130,
    maximumValueOfMonth: 12.6888,
    minimumValueOfYear: 0.8130,
    maximumValueOfYear: 12.6888,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/375px-Flag_of_India.svg.png',
    currencyName: 'Hindistan Rupisi',
    currencySymbolName: 'INR',
    buyPrice: 0.4093,
    sellPrice: 0.4095,
    lastPrice: 0.4095,
    changedValueOfDay: 0,
    changedPercentageOfDay: 0.31,
    changedPercentageOfWeek: 0.36,
    changedPercentageOfMonth: 0.46,
    changedPercentageOfThreeMonth: 1.32,
    changedPercentageOfYear: 18.14,
    minimumValueOfDay: 0.0008,
    maximumValueOfDay: 0.4093,
    minimumValueOfMonth: 0.0008,
    maximumValueOfMonth: 0.4094,
    minimumValueOfYear: 0.0007,
    maximumValueOfYear: 3.7325,
  ),
  Currency(
    currencyImage:
        'https://w7.pngwing.com/pngs/540/310/png-transparent-flag-of-saudi-arabia-national-flag-flag-of-the-united-states-flag-miscellaneous-angle-flag.png',
    currencyName: 'Suudi Arabistan Riyali',
    currencySymbolName: 'SAR',
    buyPrice: 9.1544,
    sellPrice: 9.1823,
    lastPrice: 9.1823,
    changedValueOfDay: 0.03,
    changedPercentageOfDay: 0.28,
    changedPercentageOfWeek: 0.16,
    changedPercentageOfMonth: 0.66,
    changedPercentageOfYear: 20,
    changedPercentageOfThreeMonth: 2.18,
    minimumValueOfDay: 9.1302,
    maximumValueOfDay: 9.2379,
    minimumValueOfMonth: 9.0283,
    maximumValueOfMonth: 9.2379,
    minimumValueOfYear: 7.5941,
    maximumValueOfYear: 9.2379,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/375px-Flag_of_Indonesia.svg.png',
    currencyName: 'Endonezya Rupiahi',
    currencySymbolName: 'IDR',
    buyPrice: 0.0022,
    sellPrice: 0.0022,
    lastPrice: 0.0022,
    changedValueOfDay: 0,
    changedPercentageOfDay: 0.29,
    changedPercentageOfWeek: 0.32,
    changedPercentageOfMonth: -1.37,
    changedPercentageOfThreeMonth: 0.76,
    changedPercentageOfYear: 17.55,
    minimumValueOfDay: 0.0022,
    maximumValueOfDay: 5.9503,
    minimumValueOfMonth: 0.0022,
    maximumValueOfMonth: 6.0925,
    minimumValueOfYear: 0.0018,
    maximumValueOfYear: 6.70,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/375px-Flag_of_the_Philippines.svg.png',
    currencyName: 'Filipinler Pesosu',
    currencySymbolName: 'PHP',
    buyPrice: 0.5863,
    sellPrice: 0.5864,
    lastPrice: 0.5864,
    changedValueOfDay: 0,
    changedPercentageOfDay: 0.21,
    changedPercentageOfWeek: 0,
    changedPercentageOfMonth: -1.08,
    changedPercentageOfThreeMonth: -2.22,
    changedPercentageOfYear: 12.75,
    minimumValueOfDay: 0.0690,
    maximumValueOfDay: 0.5863,
    minimumValueOfMonth: 0.0690,
    maximumValueOfMonth: 0.5911,
    minimumValueOfYear: 0.0618,
    maximumValueOfYear: 0.6129,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/300px-Flag_of_Syria.svg.png',
    currencyName: 'Suriye Lirası',
    currencySymbolName: 'SYP',
    buyPrice: 0.0027,
    sellPrice: 0.0027,
    lastPrice: 0.0027,
    changedValueOfDay: 0,
    changedPercentageOfDay: 0.29,
    changedPercentageOfWeek: 0.24,
    changedPercentageOfMonth: 0.74,
    changedPercentageOfThreeMonth: 1.92,
    changedPercentageOfYear: 19.88,
    minimumValueOfDay: 0.0027,
    maximumValueOfDay: 0.0028,
    maximumValueOfMonth: 0.025,
    maximumValueOfYear: 0.028,
    minimumValueOfMonth: 0.024,
    minimumValueOfYear: 0.020,
  ),
  Currency(
    currencyImage:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_7tKFVAG2kflyh9TNPjDT08oGIcegsJhzPw&s',
    currencyName: 'Azerbaycan Manatı',
    currencySymbolName: 'AZN',
    buyPrice: 20.2488,
    sellPrice: 20.2626,
    lastPrice: 20.2626,
    changedValueOfDay: 0.06,
    changedPercentageOfDay: 0.30,
    changedPercentageOfWeek: 0.15,
    changedPercentageOfMonth: 0.80,
    changedPercentageOfThreeMonth: 2.23,
    changedPercentageOfYear: 26.81,
    minimumValueOfDay: 0.0343,
    maximumValueOfDay: 20.2557,
    minimumValueOfMonth: 0.0343,
    maximumValueOfMonth: 20.2576,
    minimumValueOfYear: 0.0343,
    maximumValueOfYear: 20.2576,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/375px-Flag_of_Colombia.svg.png',
    currencyName: 'Kolombiya Pesosu',
    currencySymbolName: 'COP',
    buyPrice: 0.0079,
    sellPrice: 0.0079,
    lastPrice: 0.0079,
    changedValueOfDay: 0,
    changedPercentageOfDay: 0.15,
    changedPercentageOfWeek: 1.56,
    changedPercentageOfMonth: -2.09,
    changedPercentageOfThreeMonth: -5.45,
    changedPercentageOfYear: 10.96,
    minimumValueOfDay: 0.0079,
    maximumValueOfDay: 20.6020,
    minimumValueOfMonth: 0.0077,
    maximumValueOfMonth: 20.7940,
    minimumValueOfYear: 0.0071,
    maximumValueOfYear: 41.6500,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/1200px-Flag_of_the_United_Arab_Emirates.svg.png',
    currencyName: 'BAE Dirhemi',
    currencySymbolName: 'AED',
    buyPrice: 9.3727,
    sellPrice: 9.379,
    lastPrice: 9.379,
    changedValueOfDay: 0.03,
    changedPercentageOfDay: 0.28,
    changedPercentageOfWeek: 0.16,
    changedPercentageOfMonth: 0.71,
    changedPercentageOfThreeMonth: 2.28,
    changedPercentageOfYear: 20.19,
    minimumValueOfDay: 9.3258,
    maximumValueOfDay: 9.4839,
    maximumValueOfMonth: 9.4839,
    maximumValueOfYear: 9.4839,
    minimumValueOfMonth: 9.2326,
    minimumValueOfYear: 7.7554,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/250px-Flag_of_the_United_States.svg.png',
    currencyName: 'Amerikan Doları',
    currencySymbolName: 'USD',
    buyPrice: 34.4229,
    sellPrice: 34.4465,
    lastPrice: 34.4465,
    changedValueOfDay: 0.10,
    changedPercentageOfDay: 0.30,
    changedPercentageOfWeek: 0.15,
    changedPercentageOfMonth: 0.80,
    changedPercentageOfThreeMonth: 2.23,
    changedPercentageOfYear: 20.17,
    minimumValueOfDay: 34.2525,
    maximumValueOfDay: 34.8345,
    minimumValueOfMonth: 33.9112,
    maximumValueOfMonth: 34.8345,
    minimumValueOfYear: 28.4435,
    maximumValueOfYear: 34.8345,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/800px-Flag_of_Oman.svg.png',
    currencyName: 'Umman Riyali',
    currencySymbolName: 'OMR',
    buyPrice: 89.4252,
    sellPrice: 89.4675,
    lastPrice: 89.4675,
    changedValueOfDay: 0.27,
    changedPercentageOfDay: 0.30,
    changedPercentageOfWeek: 0.20,
    changedPercentageOfMonth: 0.61,
    changedPercentageOfThreeMonth: 2.24,
    minimumValueOfDay: 0.0692,
    changedPercentageOfYear: 20.04,
    maximumValueOfDay: 89.4385,
    minimumValueOfMonth: 0.0692,
    maximumValueOfMonth: 89.5216,
    minimumValueOfYear: 0.0611,
    maximumValueOfYear: 89.5216,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/375px-Flag_of_Argentina.svg.png',
    currencyName: 'Arjantin Pesosu',
    currencySymbolName: 'ARS',
    buyPrice: 0.0344,
    sellPrice: 0.0344,
    lastPrice: 0.0344,
    changedValueOfDay: 0,
    changedPercentageOfDay: 0.20,
    changedPercentageOfWeek: -0.23,
    changedPercentageOfMonth: -1.19,
    changedPercentageOfThreeMonth: -4.07,
    changedPercentageOfYear: -57.49,
    minimumValueOfDay: 0.0344,
    maximumValueOfDay: 5.1750,
    minimumValueOfMonth: 0.0342,
    maximumValueOfMonth: 5.2520,
    minimumValueOfYear: 0.0342,
    maximumValueOfYear: 10.4340,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/375px-Flag_of_Bahrain.svg.png',
    currencyName: 'Bahreyn Dinarı',
    currencySymbolName: 'BHD',
    buyPrice: 91.6506,
    sellPrice: 91.6756,
    lastPrice: 91.6756,
    changedValueOfDay: 0.19,
    changedPercentageOfDay: 0.21,
    changedPercentageOfWeek: 0.32,
    changedPercentageOfMonth: 0.87,
    changedPercentageOfThreeMonth: 1.96,
    changedPercentageOfYear: 19.76,
    minimumValueOfDay: 1.9041,
    maximumValueOfDay: 91.6734,
    minimumValueOfMonth: 1.8723,
    maximumValueOfMonth: 91.6877,
    minimumValueOfYear: 1.5154,
    maximumValueOfYear: 91.6877,
  ),


  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg',
    currencyName: 'İzlanda Kronası',
    currencySymbolName: 'ISK',
    buyPrice: 0.2498,
    sellPrice: 0.2499,
    lastPrice: 0.2499,
    changedValueOfDay: 0,
    changedPercentageOfDay: 0.78,
    changedPercentageOfWeek: 0.82,
    changedPercentageOfMonth: 0.17,
    changedPercentageOfThreeMonth: 2.60,
    changedPercentageOfYear: 23.24,
    minimumValueOfDay: 0.2499,
    maximumValueOfDay: 4.4294,
    minimumValueOfMonth: 0.2464,
    maximumValueOfMonth: 4.4316,
    minimumValueOfYear: 0.1988,
    maximumValueOfYear: 4.4845,
  ),
  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/250px-Flag_of_Lebanon.svg.png',
    currencyName: 'Lübnan Lirası',
    currencySymbolName: 'LBP',
    buyPrice: 0.0004,
    sellPrice: 0.0004,
    lastPrice: 0.0004,
    changedValueOfDay: 0,
    changedPercentageOfDay: 0.35,
    changedPercentageOfWeek: 0.79,
    changedPercentageOfMonth: 0.71,
    changedPercentageOfThreeMonth: 2.30,
    changedPercentageOfYear: -79.83,
    minimumValueOfDay: 0.0004,
    maximumValueOfDay: 0.0696,
    minimumValueOfMonth: 0.004,
    maximumValueOfMonth: 0.0713,
    minimumValueOfYear: 0.0003,
    maximumValueOfYear: 0.0746,
  ),
  Currency(
    currencyImage:
        'https://assets.wikiwand.com/_next/image?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F7%2F77%2FFlag_of_Hejaz_1917.svg%2F320px-Flag_of_Hejaz_1917.svg.png&w=2048&q=75',
    currencyName: 'Ürdün Dinarı',
    currencySymbolName: 'JOD',
    buyPrice: 48.5445,
    sellPrice: 48.5778,
    lastPrice: 48.5778,
    changedValueOfDay: 0.12,
    changedPercentageOfDay: 0.24,
    changedPercentageOfWeek: 0.22,
    changedPercentageOfMonth: 0.54,
    changedPercentageOfThreeMonth: 2.16,
    changedPercentageOfYear: 20.15,
    minimumValueOfDay: 4.4159,
    maximumValueOfDay: 48.5611,
    minimumValueOfMonth: 4.3923,
    maximumValueOfMonth: 48.5611,
    minimumValueOfYear: 3.6537,
    maximumValueOfYear: 48.5611,
  ),
  Currency(
    currencyImage:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOkxOEW_qI2en58FR3X0e5ARXJY5yu2xR3ZA&s',
    currencyName: 'Ukrayna Grivnası',
    currencySymbolName: 'UAH',
    buyPrice: 0.8295,
    sellPrice: 0.83,
    lastPrice: 0.83,
    changedValueOfDay: 0,
    changedPercentageOfDay: -0.29,
    changedPercentageOfWeek: 0.21,
    changedPercentageOfMonth: 0.41,
    changedPercentageOfThreeMonth: 1.24,
    changedPercentageOfYear: 4.92,
    minimumValueOfDay: 0.0026,
    maximumValueOfDay: 0.8297,
    minimumValueOfMonth: 0.0026,
    maximumValueOfMonth: 0.8325,
    minimumValueOfYear: 0.0022,
    maximumValueOfYear: 0.8350,
  ),

  Currency(
    currencyImage:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/1200px-Flag_of_Qatar.svg.png',
    currencyName: 'Katar Riyali',
    currencySymbolName: 'QAR',
    buyPrice: 9.4509,
    sellPrice: 9.4645,
    lastPrice: 9.4645,
    changedValueOfDay: 0.03,
    changedPercentageOfDay: 0.27,
    changedPercentageOfWeek: 0.14,
    changedPercentageOfMonth: 0.73,
    changedPercentageOfThreeMonth: 2.28,
    changedPercentageOfYear: 20.16,
    minimumValueOfDay: 9.4187,
    maximumValueOfDay: 9.53,
    minimumValueOfMonth: 9.3210,
    maximumValueOfMonth: 9.53,
    minimumValueOfYear: 7.8120,
    maximumValueOfYear: 9.8360,
  ),

];
